### ISSUE TITLE
data-multiple don't working

### ISSUE THREAD

**Issue by theaqua** [uploadcare/angular-uploadcare#7]
Probably because AngularJS changes `data-multiple="multiple"` to `"multiple="multiple"` and uploadcare widget receives incorrect option.

**Comment by avsd** [comment]
It seems to be unrelated to AngularJS changes. What exactly does not work?

Can you provide an example?

**Comment by theaqua** [comment]
http://plnkr.co/edit/bAPqi7268lJJoKe7PyH5?p=preview

**Comment by dmitry-mukhin** [comment]
Is this expected Angular behavior? Seems like a weird err on it's part.

**Comment by theaqua** [comment]
I update plunk: http://plnkr.co/edit/bAPqi7268lJJoKe7PyH5?p=preview
As you see in DOM, `data-multiple` saved in `div` and `input`.

**Comment by dmitry-mukhin** [comment]
Well, the problem is with directive, not arbitrary DOM elements.

**Comment by dmitry-mukhin** [comment]
OK, I don't know angular at all, so please double check this.
1. seems that this is a bug in Angular that happens when directive is "replacing"
2. "replacing" is deprecated, so there is no hope that this will get fixed
3. this seems to work: http://plnkr.co/edit/vByG5B4NOf8ye4KR0U1K?p=preview

If you can verify that this works for you too, we'll change directive behavior to not using replacement.

**Comment by theaqua** [comment]
Now it working fine, thanks!
